Add null object
yiisoft/session pull request #39
Opened 2022-10-21 21:26 UTC by xepozz

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌

2022-10-22 03:21 UTC, vjik commented
Maybe create "in memory session" (save and get data from private properties) instead of "null session"?

2022-10-22 06:10 UTC, xepozz commented
You may create it if it is needed

2022-10-22 12:25 UTC, vjik commented
> You may create it if it is needed

If create in memory, then null not need

2022-10-22 14:13 UTC, xepozz commented
https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it

2022-10-22 15:14 UTC, vjik commented
I write "maybe". I not need both :)

2022-10-22 15:16 UTC, vjik requested changes
Need changelog and tests

2022-10-25 00:31 UTC, xepozz commented
There is nothing to test

2022-10-25 06:57 UTC, vjik commented on CHANGELOG.md
> +- Enh #39: Add NullSession (@xepozz)
```suggestion
- New #39: Add `NullSession` (@xepozz)
```

2022-10-25 06:58 UTC, vjik commented
> There is nothing to test

Need test get and pull default values. Also can test other methods work without exceptions.
Need tests coverage 100%.

2022-10-26 12:21 UTC, samdark approved these changes

2022-10-28 19:16 UTC, merged